#ifndef MONITORINGSYSTEM_SRC_AGENTS_CORE_DEFS_H_
#define MONITORINGSYSTEM_SRC_AGENTS_CORE_DEFS_H_

#define BUFFER_SIZE 1000

#define unused(x) ((void)(x))

#endif // MONITORINGSYSTEM_SRC_AGENTS_CORE_DEFS_H_

